import { NextResponse } from "next/server";
import { dbConnect, getCachedPlayers } from "../../../../lib/mongodb";
import GameSession from "../../../../models/GameSession";
import Player from "../../../../models/Player";
import { questionEngine } from "../../../../lib/questionEngine";
import { generateIntelligenceReport } from "../../../../lib/gemini";

export async function POST(req: Request) {
  try {
    await dbConnect();
    const body = await req.json();
    const { gameId, questionId, answer } = body;

    if (!gameId || !questionId || !answer) {
      return NextResponse.json({ error: "Missing input metrics." }, { status: 400 });
    }

    // 1. Load active game state
    const session = await GameSession.findById(gameId);
    if (!session) {
      return NextResponse.json({ error: "Inference session missing." }, { status: 404 });
    }

    // 2. Pull overall player pool for distribution management (Using Blazing Fast Memory Cache)
    const allPlayers = await getCachedPlayers();
    
    // Ensure Mongoose map is instantiated correctly
    const currentMap = session.playerProbabilities instanceof Map 
      ? session.playerProbabilities 
      : new Map(Object.entries(session.playerProbabilities || {}));

    // 3. Run core Bayesian Updating Pipeline (pass dynamicQuestion if it is a dynamic query)
    const { 
      updatedProbabilities, 
      activeCount, 
      filterLog, 
      reductionLog 
    } = questionEngine.evaluateBayesianAnswer(
      allPlayers,
      currentMap,
      Number(questionId),
      answer,
      session.dynamicQuestion
    );

    // Update session probability map back to document
    session.playerProbabilities = updatedProbabilities;

    // Store query history log
    session.answers.push({
      questionId: Number(questionId),
      answer,
      filterLog,
      reductionLog,
    });

    // 4. Calculate state progress telemetry
    const questionsAnsweredCount = session.answers.length;
    const newConfidence = questionEngine.calculateTelemetry(updatedProbabilities, questionsAnsweredCount);

    // 5. Assess convergence conditions
    const currentTop = questionEngine.deriveLikelyCandidates(allPlayers, updatedProbabilities, 5);
    const GUESS_CONFIDENCE_THRESHOLD = 75;

    // Confidence-driven completion:
    // - Guess when confidence reaches threshold
    // - Or when candidate pool is isolated
    let isComplete = newConfidence >= GUESS_CONFIDENCE_THRESHOLD || activeCount <= 1;
    let nextQuestion = null;

    if (!isComplete) {
      // Dynamic Bayesian Entropy selection via Facade
      nextQuestion = await questionEngine.getNextOptimalQuestion(
        allPlayers,
        updatedProbabilities,
        session.askedQuestions
      );

      if (nextQuestion) {
        // Track question as asked
        session.askedQuestions.push(nextQuestion.id);
        
        // Save the dynamic question evaluations mapping if generated by Gemini
        if (nextQuestion.dynamicQuestionData) {
          session.dynamicQuestion = nextQuestion.dynamicQuestionData;
          session.markModified("dynamicQuestion");
        } else {
          session.dynamicQuestion = undefined;
        }
      } else {
        // Zero informational variance left, forcing completion
        isComplete = true;
      }
    }

    // Update Session Document properties
    session.confidence = newConfidence;
    
    if (isComplete) {
      session.ended = true;
      // Set the highest probable player as prediction target
      if (currentTop.length > 0) {
        const targetPlayer = currentTop[0].player;
        session.predictedPlayer = targetPlayer._id;

        // Trigger background pre-generation of the Gemini intelligence report (do not await it!)
        generateIntelligenceReport(
          targetPlayer.name,
          targetPlayer.keyStrength || targetPlayer.role
        ).then(async (aiInsight) => {
          if (aiInsight) {
            await GameSession.updateOne(
              { _id: session._id },
              { $set: { predictedPlayerInsight: aiInsight } }
            );
            console.log("Background Task: Successfully pre-cached dynamic intelligence report in GameSession.");
          }
        }).catch((err) => {
          console.error("Background Task: Failed to pre-generate report:", err);
        });
      }
    }

    // Force MongoDB change tracking on Map field
    session.markModified("playerProbabilities");
    await session.save();

    // 7. Return strictly formatted schema + UI support logs
    return NextResponse.json({
      nextQuestion,
      remainingPlayers: activeCount,
      confidence: newConfidence,
      topPredictions: currentTop.map((t) => ({
        name: t.player.name,
        probability: t.probability,
      })),
      isComplete,
      logs: [
        {
          filter: filterLog,
          reduction: reductionLog,
          type: answer === "YES" ? "check_circle" : answer === "NO" ? "cancel" : answer === "MAYBE" ? "help" : "help_outline",
        },
      ],
    });
  } catch (error: any) {
    console.error("Submit answer Bayesian failure:", error);
    return NextResponse.json({ error: "Mathematical calculators failed during inference loop." }, { status: 500 });
  }
}
