import { IPlayer } from "../models/Player";

export interface IQuestionDef {
  id: number;
  text: string;
  subtitle: string;
  attribute: string;
  evaluator: (player: IPlayer) => boolean;
  weight: number;
  category: string;
  dynamicEvaluations?: Record<string, string>;
}

export const questionsList: IQuestionDef[] = [
  {
    id: 1,
    text: "Is the player an Indian national?",
    subtitle: "Counts as a domestic player rather than occupying an overseas slot.",
    attribute: "overseas",
    evaluator: (p) => p.overseas === false,
    weight: 1.5,
    category: "Demographic",
  },
  {
    id: 2,
    text: "Is the player a designated wicketkeeper?",
    subtitle: "Frequently stands behind the stumps with gloves.",
    attribute: "wicketkeeper",
    evaluator: (p) => p.wicketkeeper === true,
    weight: 1.2,
    category: "Role",
  },
  {
    id: 3,
    text: "Has the player ever captained an IPL franchise?",
    subtitle: "Served as a captain in a match or for a prolonged duration.",
    attribute: "captain",
    evaluator: (p) => p.captain === true,
    weight: 1.1,
    category: "Role",
  },
  {
    id: 4,
    text: "Is the player currently active in professional cricket?",
    subtitle: "Has not officially announced retirement from IPL/all formats.",
    attribute: "active",
    evaluator: (p) => p.active === true,
    weight: 1.4,
    category: "Status",
  },
  {
    id: 5,
    text: "Is the player primarily a batsman?",
    subtitle: "Their core role in the lineup is to score runs.",
    attribute: "role",
    evaluator: (p) => p.role.toLowerCase().includes("batsman") || p.role.toLowerCase().includes("keeper"),
    weight: 1.0,
    category: "Role",
  },
  {
    id: 6,
    text: "Is the player a bowler?",
    subtitle: "Primary responsibility is taking wickets and bowling 4 overs.",
    attribute: "role",
    evaluator: (p) => p.role.toLowerCase().includes("bowler"),
    weight: 1.0,
    category: "Role",
  },
  {
    id: 7,
    text: "Is the player an all-rounder?",
    subtitle: "Contributes significantly with both bat and ball.",
    attribute: "role",
    evaluator: (p) => p.role.toLowerCase().includes("all-rounder"),
    weight: 1.1,
    category: "Role",
  },
  {
    id: 8,
    text: "Does the player bat left-handed?",
    subtitle: "Attacking or defending from the left side.",
    attribute: "battingStyle",
    evaluator: (p) => p.battingStyle.toLowerCase().includes("left-hand"),
    weight: 1.0,
    category: "Role",
  },
  {
    id: 9,
    text: "Has the player ever represented Chennai Super Kings (CSK)?",
    subtitle: "Worn the yellow jersey in any IPL season.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("CSK"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 10,
    text: "Has the player ever represented Royal Challengers Bengaluru (RCB)?",
    subtitle: "Worn the red and black/gold jersey.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("RCB"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 11,
    text: "Has the player ever represented Mumbai Indians (MI)?",
    subtitle: "Worn the blue and gold jersey.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("MI"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 12,
    text: "Has the player ever represented Kolkata Knight Riders (KKR)?",
    subtitle: "Played for the purple and gold KKR squad.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("KKR"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 13,
    text: "Has the player ever represented Rajasthan Royals (RR)?",
    subtitle: "Played for the inaugural champions.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("RR"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 14,
    text: "Has the player ever played for Sunrisers Hyderabad (SRH) or Deccan Chargers?",
    subtitle: "Represented Hyderabad franchises in the IPL.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("SRH") || p.teams.includes("Deccan Chargers"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 15,
    text: "Does the player bowl spin?",
    subtitle: "Includes off-spin, leg-spin, chinaman, or orthodox spin.",
    attribute: "bowlingStyle",
    evaluator: (p) =>
      p.bowlingStyle.toLowerCase().includes("spin") ||
      p.bowlingStyle.toLowerCase().includes("legbreak") ||
      p.bowlingStyle.toLowerCase().includes("offbreak") ||
      p.bowlingStyle.toLowerCase().includes("chinaman") ||
      p.bowlingStyle.toLowerCase().includes("orthodox"),
    weight: 1.0,
    category: "Role",
  },
  {
    id: 16,
    text: "Does the player bowl fast or medium pace?",
    subtitle: "Uses pace, seam, and swing rather than turn.",
    attribute: "bowlingStyle",
    evaluator: (p) =>
      p.bowlingStyle.toLowerCase().includes("fast") ||
      p.bowlingStyle.toLowerCase().includes("medium") ||
      p.bowlingStyle.toLowerCase().includes("pace"),
    weight: 1.0,
    category: "Role",
  },
  {
    id: 17,
    text: "Is the player from Australia?",
    subtitle: "A prominent Aussie representation.",
    attribute: "country",
    evaluator: (p) => p.country.toLowerCase() === "australia",
    weight: 1.2,
    category: "Demographic",
  },
  {
    id: 18,
    text: "Is the player from South Africa?",
    subtitle: "Hails from the rainbow nation.",
    attribute: "country",
    evaluator: (p) => p.country.toLowerCase() === "south africa",
    weight: 1.2,
    category: "Demographic",
  },
  {
    id: 19,
    text: "Is the player from West Indies?",
    subtitle: "Hails from the Caribbean islands.",
    attribute: "country",
    evaluator: (p) => p.country.toLowerCase().includes("west indies") || p.country.toLowerCase().includes("caribbean"),
    weight: 1.2,
    category: "Demographic",
  },
  {
    id: 20,
    text: "Has the player ever played for Delhi Capitals (DC / DD)?",
    subtitle: "Represented the capital franchise.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("DC") || p.teams.includes("DD"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 21,
    text: "Has the player ever played for Punjab Kings (PBKS / KXIP)?",
    subtitle: "Played for the Mohali-based franchise.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("PBKS") || p.teams.includes("KXIP"),
    weight: 1.0,
    category: "Teams",
  },
  {
    id: 22,
    text: "Has the player ever played for Gujarat Titans (GT)?",
    subtitle: "Represented the Ahmedabad franchise introduced in 2022.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("GT"),
    weight: 1.1,
    category: "Teams",
  },
  {
    id: 23,
    text: "Has the player ever played for Lucknow Super Giants (LSG)?",
    subtitle: "Represented the Lucknow franchise introduced in 2022.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("LSG"),
    weight: 1.1,
    category: "Teams",
  },
  {
    id: 24,
    text: "Is the player from England?",
    subtitle: "Represented the three lions in English cricket.",
    attribute: "country",
    evaluator: (p) => p.country.toLowerCase() === "england",
    weight: 1.2,
    category: "Demographic",
  },
  {
    id: 25,
    text: "Is the player from Sri Lanka or New Zealand?",
    subtitle: "Hails from Sri Lanka or New Zealand.",
    attribute: "country",
    evaluator: (p) => p.country.toLowerCase() === "sri lanka" || p.country.toLowerCase() === "new zealand",
    weight: 1.2,
    category: "Demographic",
  },
  // Expanded Dimension Queries
  {
    id: 26,
    text: "Is the player officially retired from IPL/professional cricket?",
    subtitle: "No longer playing in standard commercial formats.",
    attribute: "retired",
    evaluator: (p) => p.retired === true,
    weight: 1.4,
    category: "Status",
  },
  {
    id: 27,
    text: "Did the player make their IPL debut in the inaugural 2008 season?",
    subtitle: "Part of the original starting era of the league.",
    attribute: "debutYear",
    evaluator: (p) => p.debutYear === 2008,
    weight: 1.3,
    category: "History",
  },
  {
    id: 28,
    text: "Has the player won at least one IPL title?",
    subtitle: "Been part of a squad that lifted the cup.",
    attribute: "iplTitles",
    evaluator: (p) => p.iplTitles > 0,
    weight: 1.1,
    category: "Success",
  },
  {
    id: 29,
    text: "Has the player won 3 or more IPL titles?",
    subtitle: "Elite serial winner bracket.",
    attribute: "iplTitles",
    evaluator: (p) => p.iplTitles >= 3,
    weight: 1.2,
    category: "Success",
  },
  {
    id: 30,
    text: "Did the player debut in or after 2018?",
    subtitle: "Represents the modern younger generation / recent domestic additions.",
    attribute: "debutYear",
    evaluator: (p) => p.debutYear >= 2018,
    weight: 1.3,
    category: "History",
  },
  {
    id: 31,
    text: "Has the player represented multiple IPL franchises?",
    subtitle: "Played for more than one team across IPL seasons.",
    attribute: "teams",
    evaluator: (p) => p.teams.length > 1,
    weight: 1.2,
    category: "Career",
  },
  {
    id: 32,
    text: "Has the player represented only one IPL franchise?",
    subtitle: "Single-franchise career profile.",
    attribute: "teams",
    evaluator: (p) => p.teams.length === 1,
    weight: 1.1,
    category: "Career",
  },
  {
    id: 33,
    text: "Did the player debut between 2008 and 2012?",
    subtitle: "Belongs to IPL's early foundational era.",
    attribute: "debutYear",
    evaluator: (p) => p.debutYear >= 2008 && p.debutYear <= 2012,
    weight: 1.2,
    category: "History",
  },
  {
    id: 34,
    text: "Did the player debut in 2020 or later?",
    subtitle: "Represents the newest IPL generation.",
    attribute: "debutYear",
    evaluator: (p) => p.debutYear >= 2020,
    weight: 1.2,
    category: "History",
  },
  {
    id: 35,
    text: "Is the player an overseas all-rounder?",
    subtitle: "Foreign player contributing in both batting and bowling.",
    attribute: "role",
    evaluator: (p) => p.overseas === true && p.role.toLowerCase().includes("all-rounder"),
    weight: 1.3,
    category: "Role",
  },
  {
    id: 36,
    text: "Is the player an active wicketkeeper?",
    subtitle: "A currently active player who keeps wickets.",
    attribute: "wicketkeeper",
    evaluator: (p) => p.wicketkeeper === true && p.active === true,
    weight: 1.3,
    category: "Role",
  },
  {
    id: 37,
    text: "Has the player won 2 or more IPL titles?",
    subtitle: "Multi-time IPL champion profile.",
    attribute: "iplTitles",
    evaluator: (p) => p.iplTitles >= 2,
    weight: 1.2,
    category: "Success",
  },
  {
    id: 38,
    text: "Has the player never won an IPL title?",
    subtitle: "No title-winning season recorded.",
    attribute: "iplTitles",
    evaluator: (p) => p.iplTitles === 0,
    weight: 1.1,
    category: "Success",
  },
  {
    id: 39,
    text: "Is the player a left-arm bowler?",
    subtitle: "Bowls with left arm (pace or spin).",
    attribute: "bowlingStyle",
    evaluator: (p) => p.bowlingStyle.toLowerCase().includes("left-arm"),
    weight: 1.1,
    category: "Role",
  },
  {
    id: 40,
    text: "Is the player primarily a right-arm spinner?",
    subtitle: "Off-spin, leg-spin, chinaman, or orthodox spin.",
    attribute: "bowlingStyle",
    evaluator: (p) =>
      p.bowlingStyle.toLowerCase().includes("offbreak") ||
      p.bowlingStyle.toLowerCase().includes("legbreak") ||
      p.bowlingStyle.toLowerCase().includes("chinaman") ||
      p.bowlingStyle.toLowerCase().includes("orthodox"),
    weight: 1.1,
    category: "Role",
  },
  {
    id: 41,
    text: "Has the player represented both Mumbai Indians and Chennai Super Kings?",
    subtitle: "Played for both of IPL's most successful franchises.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("MI") && p.teams.includes("CSK"),
    weight: 1.3,
    category: "Teams",
  },
  {
    id: 42,
    text: "Has the player represented either Gujarat Titans or Lucknow Super Giants?",
    subtitle: "Played for one of the expansion-era franchises.",
    attribute: "teams",
    evaluator: (p) => p.teams.includes("GT") || p.teams.includes("LSG"),
    weight: 1.1,
    category: "Teams",
  },
];

export function getQuestionById(id: number): IQuestionDef | undefined {
  return questionsList.find((q) => q.id === id);
}
