const fs = require('fs');
const path = require('path');

const playersFilePath = path.join(__dirname, '../data/players.json');

// Load existing players
let players = [];
if (fs.existsSync(playersFilePath)) {
  try {
    players = JSON.parse(fs.readFileSync(playersFilePath, 'utf8'));
  } catch (e) {
    console.error("Failed reading players.json", e);
  }
}

console.log("Original players.json size:", players.length);

const lastTwenty = [
  {
    name: "Stuart Binny",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["RR", "RCB", "MI"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2010,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "880",
    playingStyle: "Utility Swing Bowler All-rounder",
    keyStrength: "Flick shots off pads and medium-pace swing",
    eraGeneration: "Historical Legends",
    signatureMetric: "Best bowling figures for India in ODIs (6/4)"
  },
  {
    name: "Vinay Kumar",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RCB", "MI", "KKR", "Kochi Tuskers"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "310",
    playingStyle: "Experienced Medium Pacer",
    keyStrength: "Deceptive slower balls and outswingers",
    eraGeneration: "Historical Legends",
    signatureMetric: "Karnataka Domestic Legend / Davangere Express"
  },
  {
    name: "Karun Nair",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RR", "DC", "PBKS", "KKR", "RCB", "LSG"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2013,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,496",
    playingStyle: "Technically Gifted Strokeplayer",
    keyStrength: "Excellent sweep shots and late cuts against spin",
    eraGeneration: "Modern Era",
    signatureMetric: "India's second Triple Centurion in Tests"
  },
  {
    name: "Lakshmipathy Balaji",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["CSK", "KKR", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "36",
    playingStyle: "Deceptive Swing Bowler",
    keyStrength: "Elite change of pace and skiddy bouncers",
    eraGeneration: "Historical Legends",
    signatureMetric: "First-ever IPL Hat-trick (2008)"
  },
  {
    name: "Joginder Sharma",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "36",
    playingStyle: "Medium Pace Swing Bowler",
    keyStrength: "Immensely composed in death overs and skiddy swing",
    eraGeneration: "Historical Legends",
    signatureMetric: "2007 T20 World Cup Final Hero"
  },
  {
    name: "Rishi Dhawan",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast",
    teams: ["PBKS", "MI", "SRH"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "163",
    playingStyle: "Clever Medium-pace Utility Bowler",
    keyStrength: "Searing slow cutter and skiddy outswing",
    eraGeneration: "Modern Era",
    signatureMetric: "Himachal Pradesh Domestic Champion"
  },
  {
    name: "Pawan Negi",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["RCB", "CSK", "DD", "KKR"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2012,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "365",
    playingStyle: "Flat Left-arm Spinner / Pinch Hitter",
    keyStrength: "Firing flat left-arm spin & handy late order sixes",
    eraGeneration: "Historical Legends",
    signatureMetric: "Highest paid uncapped player (auction buy 8.5 Cr)"
  },
  {
    name: "Shahbaz Nadeem",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["SRH", "DD"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2011,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "32",
    playingStyle: "Classical left-arm spinner",
    keyStrength: "High arm action, flat lines, immense accuracy",
    eraGeneration: "Historical Legends",
    signatureMetric: "Jharkhand Domestic Spin Icon"
  },
  {
    name: "Parvez Rasool",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RCB", "SRH", "PWI"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2013,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "120",
    playingStyle: "Middle-order Offspinning All-rounder",
    keyStrength: "Tight lines, drift, and handy placement batting",
    eraGeneration: "Historical Legends",
    signatureMetric: "First Jammu & Kashmir player to play for India"
  },
  {
    name: "Murali Kartik",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["KKR", "RCB", "PWI", "KXIP"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "70",
    playingStyle: "Classical Left-arm Spinner",
    keyStrength: "Outstanding classical flight, drift, and spin",
    eraGeneration: "Historical Legends",
    signatureMetric: "Indian International Spin Maestro"
  },
  {
    name: "Barinder Sran",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["SRH", "MI", "KXIP", "RR"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 2,
    debutYear: 2015,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "4",
    playingStyle: "Left-arm Seamer",
    keyStrength: "Early swing and skiddy short-pitched bowling",
    eraGeneration: "Historical Legends",
    signatureMetric: "SRH Championship Winning Bowler (2016)"
  },
  {
    name: "Manpreet Gony",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["CSK", "KXIP", "MI", "Deccan Chargers"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "99",
    playingStyle: "Hit-the-deck Heavy Bowler",
    keyStrength: "Fierce hard lengths and powerful lower-order hits",
    eraGeneration: "Historical Legends",
    signatureMetric: "Breakout star of CSK's 2008 campaign"
  },
  {
    name: "Sudeep Tyagi",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["CSK", "SRH"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2009,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2",
    playingStyle: "Skiddy Medium Pacer",
    keyStrength: "Outswingers and skiddy bouncers",
    eraGeneration: "Historical Legends",
    signatureMetric: "India International Speedster"
  },
  {
    name: "Abhimanyu Mithun",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RCB", "MI", "SRH"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2010,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "34",
    playingStyle: "Heavy Seamer",
    keyStrength: "Hitting the deck hard and skiddy bouncers",
    eraGeneration: "Historical Legends",
    signatureMetric: "Hat-trick in Ranji, Vijay Hazare, and Syed Mushtaq"
  },
  {
    name: "Gurkeerat Singh Mann",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RCB", "PBKS", "GT", "DD"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2012,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "511",
    playingStyle: "Aggressive Middle-order Strokeplayer",
    keyStrength: "Lofted shots over covers and handy off-spin",
    eraGeneration: "Historical Legends",
    signatureMetric: "Gujarat Titans squad member"
  },
  {
    name: "Vijay Dahiya",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["DD"],
    captain: false,
    wicketkeeper: true,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "15",
    playingStyle: "Classical Keeper",
    keyStrength: "Outstanding keeping technique & clean placement",
    eraGeneration: "Historical Legends",
    signatureMetric: "India Keeper / DC Coach"
  },
  {
    name: "Ricky Bhui",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["DC", "SRH"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "145",
    playingStyle: "Middle-order Accumulator",
    keyStrength: "Flick shots off pads and spin attack",
    eraGeneration: "Modern Era",
    signatureMetric: "Andhra Captain / Ranji Star"
  },
  {
    name: "Lalit Yadav",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "305",
    playingStyle: "Gritty Utility All-rounder",
    keyStrength: "Economical off-spin and clean lofted straight hits",
    eraGeneration: "Modern Era",
    signatureMetric: "DC domestic backbone"
  },
  {
    name: "Praveen Dubey",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["DC", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2020,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "25",
    playingStyle: "Economical Legspinner",
    keyStrength: "Flatter, sliding googlies and sliders",
    eraGeneration: "Modern Era",
    signatureMetric: "Karnataka domestic spinner"
  },
  {
    name: "Vicky Ostwal",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2",
    playingStyle: "Traditional Left-arm Spinner",
    keyStrength: "Excellent dip and drift, flighting the ball",
    eraGeneration: "New Gen Rising",
    signatureMetric: "U-19 World Cup champion spinner"
  }
];

// Deduplicate based on name
const playerNames = new Set(players.map(p => p.name));
let addedCount = 0;

lastTwenty.forEach(newPlayer => {
  if (!playerNames.has(newPlayer.name)) {
    players.push(newPlayer);
    playerNames.add(newPlayer.name);
    addedCount++;
  }
});

console.log(`Added ${addedCount} brand new unique players!`);
console.log(`Total database pool size now: ${players.length}`);

// Write back to players.json
fs.writeFileSync(playersFilePath, JSON.stringify(players, null, 2), 'utf8');
console.log("players.json updated successfully.");
