const fs = require('fs');
const path = require('path');

const playersFilePath = path.join(__dirname, '../data/players.json');

// Load existing players
let players = [];
if (fs.existsSync(playersFilePath)) {
  try {
    players = JSON.parse(fs.readFileSync(playersFilePath, 'utf8'));
  } catch (e) {
    console.error("Failed reading players.json", e);
  }
}

console.log("Original players.json size:", players.length);

const evenMorePlayers = [
  {
    name: "Mukesh Kumar",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "20",
    playingStyle: "Seam & Swing Bowler",
    keyStrength: "Outstanding accuracy & death overs yorkers",
    eraGeneration: "Modern Era",
    signatureMetric: "India T20I Bowler"
  },
  {
    name: "Anrich Nortje",
    country: "South Africa",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2020,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "40",
    playingStyle: "Express Pace Bowler",
    keyStrength: "Fierce pace hitting 150kmph+ consistently",
    eraGeneration: "Modern Generation",
    signatureMetric: "One of the fastest balls in IPL history"
  },
  {
    name: "Tristan Stubbs",
    country: "South Africa",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["DC", "MI"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "390",
    playingStyle: "Power Finisher & Innovative Strokeplayer",
    keyStrength: "Elite reverse sweeps and clearing boundaries easily",
    eraGeneration: "New Gen Rising",
    signatureMetric: "DC Middle order sensation (2024)"
  },
  {
    name: "Jake Fraser-McGurk",
    country: "Australia",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "330",
    playingStyle: "Ultrafast Blaster Opener",
    keyStrength: "Savage bat speed and lofting balls in Powerplay",
    eraGeneration: "New Gen Rising",
    signatureMetric: "15-ball half century in IPL 2024"
  },
  {
    name: "Shai Hope",
    country: "West Indies",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm medium",
    teams: ["DC"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "180",
    playingStyle: "Technically Sound Anchor",
    keyStrength: "Solid defense and elegant driving against spin",
    eraGeneration: "Modern Era",
    signatureMetric: "West Indies ODI Captain"
  },
  {
    name: "Abishek Porel",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["DC"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "360",
    playingStyle: "Aggressive Wicketkeeper-Batsman",
    keyStrength: "Lofted shots over mid-wicket and skiddy sweeps",
    eraGeneration: "New Gen Rising",
    signatureMetric: "DC Impact Player star"
  },
  {
    name: "Quinton de Kock",
    country: "South Africa",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["LSG", "MI", "RCB", "SRH", "DD"],
    captain: true,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 2,
    debutYear: 2013,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "3,150",
    playingStyle: "Dynamic Left-arm Opener",
    keyStrength: "Prodigious pull shots and flick shots over square leg",
    eraGeneration: "Modern Generation",
    signatureMetric: "140* vs KKR (Highest unbeaten score)"
  },
  {
    name: "Kyle Mayers",
    country: "West Indies",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["LSG"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "379",
    playingStyle: "Powerful Left-arm Opener",
    keyStrength: "Brutal lofted straight drives and useful medium pace",
    eraGeneration: "Modern Era",
    signatureMetric: "West Indian Power Hitter"
  },
  {
    name: "Mohsin Khan",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["LSG", "MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "15",
    playingStyle: "Left-arm express bowler",
    keyStrength: "Fierce skiddy bouncers and great change-of-pace",
    eraGeneration: "Modern Era",
    signatureMetric: "Outstanding 2022 IPL season for LSG"
  },
  {
    name: "Pat Cummins",
    country: "Australia",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["SRH", "KKR", "DD"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2014,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "510",
    playingStyle: "Elite Fast Bowler & Hard Hitter",
    keyStrength: "Accurate hard-length bouncers and lightning-fast lower-order runs",
    eraGeneration: "Modern Generation",
    signatureMetric: "Led SRH to 2024 IPL Finals"
  },
  {
    name: "Cameron Green",
    country: "Australia",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RCB", "MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "700",
    playingStyle: "Tall hard-hitting all-rounder",
    keyStrength: "Monstrous drives, tall bounce, and elite fielding",
    eraGeneration: "Modern Generation",
    signatureMetric: "IPL Century for MI (2023)"
  },
  {
    name: "Glenn Maxwell",
    country: "Australia",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RCB", "PBKS", "MI", "DC"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2012,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,760",
    playingStyle: "Savage 360-degree strokeplayer",
    keyStrength: "Audacious switch hits and reverse sweeps vs spin",
    eraGeneration: "Modern Generation",
    signatureMetric: "The Big Show / Australian World Champion"
  },
  {
    name: "Rovman Powell",
    country: "West Indies",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["RR", "DC", "KKR"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "360",
    playingStyle: "Lower Order Power Hitter",
    keyStrength: "Extreme muscle-power hitting against fast bowlers",
    eraGeneration: "Modern Era",
    signatureMetric: "West Indies T20 Captain"
  },
  {
    name: "Daryl Mitchell",
    country: "New Zealand",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast",
    teams: ["CSK", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "350",
    playingStyle: "Middle Order Power Anchor",
    keyStrength: "Superb sweep shots and powerful straight drives",
    eraGeneration: "Modern Generation",
    signatureMetric: "Kiwi Clutch Operator"
  },
  {
    name: "Rachin Ravindra",
    country: "New Zealand",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "222",
    playingStyle: "Stylish Attacking Opener",
    keyStrength: "Fluent cover drives and lofted straight shots",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Kiwi World Cup breakout star"
  },
  {
    name: "Devon Conway",
    country: "New Zealand",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "924",
    playingStyle: "Impeccable Left-hand Anchor",
    keyStrength: "Flick shots off pads and sweeps vs spin",
    eraGeneration: "Modern Generation",
    signatureMetric: "CSK Final Hero (2023)"
  },
  {
    name: "Mukesh Choudhary",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "5",
    playingStyle: "Left-arm swing bowler",
    keyStrength: "Elite powerplay inward swing to right handers",
    eraGeneration: "Modern Era",
    signatureMetric: "CSK Lead Powerplay Bowler"
  },
  {
    name: "Vijaykumar Vyshak",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "20",
    playingStyle: "Smart change-of-pace Bowler",
    keyStrength: "Deceptive knuckleball and skiddy bouncers",
    eraGeneration: "Modern Era",
    signatureMetric: "RCB Emerging Domestic Bowler"
  },
  {
    name: "Akash Deep",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "35",
    playingStyle: "Hit-the-deck Fast Bowler",
    keyStrength: "Seam-up hard lengths at high pace",
    eraGeneration: "Modern Era",
    signatureMetric: "India Test Bowler"
  },
  {
    name: "Anuj Rawat",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["RCB", "RR"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "320",
    playingStyle: "Hard-hitting Keeper-Batsman",
    keyStrength: "Monstrous lofted pulls and dynamic keeping",
    eraGeneration: "Modern Era",
    signatureMetric: "RCB Opening match star (2024)"
  },
  {
    name: "Karan Sharma",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["RCB", "CSK", "MI", "SRH"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 4,
    debutYear: 2009,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "180",
    playingStyle: "Experienced Legspinner",
    keyStrength: "Fired-in legspin and handy late order sixes",
    eraGeneration: "Historical Legends",
    signatureMetric: "Only player to win 3 consecutive titles with 3 teams"
  },
  {
    name: "Mayank Agarwal",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["SRH", "PBKS", "RCB", "DC", "RPS"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2011,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,660",
    playingStyle: "Fluent Top-order Strokeplayer",
    keyStrength: "Superb inside-out lofted drives and cover drives",
    eraGeneration: "Modern Generation",
    signatureMetric: "PBKS Captain & Century Maker"
  },
  {
    name: "Glenn Phillips",
    country: "New Zealand",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["SRH", "RR"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "85",
    playingStyle: "360-degree Dynamic Finisher",
    keyStrength: "Exceptional power, acrobatic fielding & wicketkeeping",
    eraGeneration: "Modern Era",
    signatureMetric: "Smashed 3 consecutive sixes on SRH debut"
  },
  {
    name: "Jaydev Unadkat",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["SRH", "MI", "RR", "RPS", "KKR", "RCB", "DC"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2010,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "190",
    playingStyle: "Experienced Left-arm Seamer",
    keyStrength: "Elite slow cutters and skiddy bouncers",
    eraGeneration: "Historical Legends",
    signatureMetric: "Hat-trick in IPL for RPS"
  },
  {
    name: "Mayank Markande",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["SRH", "MI", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "20",
    playingStyle: "Deceptive Leg Spinner",
    keyStrength: "Fast hidden googly and skiddy sliding deliveries",
    eraGeneration: "Modern Era",
    signatureMetric: "Brilliant breakout season for MI in 2018"
  },
  {
    name: "Washington Sundar",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["SRH", "RCB", "RPS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "378",
    playingStyle: "Frugal Powerplay Offspinner",
    keyStrength: "Exceptional control in early powerplay overs",
    eraGeneration: "Modern Generation",
    signatureMetric: "RPS Powerplay Hero"
  },
  {
    name: "Aiden Markram",
    country: "South Africa",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["SRH", "PBKS"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "775",
    playingStyle: "Stylish Cover Driver",
    keyStrength: "Classical high-elbow cover drives & handy off-spin",
    eraGeneration: "Modern Generation",
    signatureMetric: "SRH SA20 Winning Captain"
  },
  {
    name: "Umran Malik",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["SRH"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "10",
    playingStyle: "Fierce Express Speed",
    keyStrength: "Consistently bowling at 150kmph+ raw velocity",
    eraGeneration: "Modern Generation",
    signatureMetric: "Emerging Player of IPL 2022 / Jammu Express"
  },
  {
    name: "Marco Jansen",
    country: "South Africa",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm fast",
    teams: ["SRH", "MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "180",
    playingStyle: "Tall Left-arm bowling all-rounder",
    keyStrength: "Prodigious left-arm swing and tall-man bouncers",
    eraGeneration: "Modern Generation",
    signatureMetric: "Tall South African Left-arm Giant"
  },
  {
    name: "Dewald Brevis",
    country: "South Africa",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "230",
    playingStyle: "Brutal 360-degree Hitter",
    keyStrength: "Audacious straight lofted drives and pull shots",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Baby AB / U-19 World Cup Legend"
  },
  {
    name: "Akash Madhwal",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "5",
    playingStyle: "Skiddy death yorker specialist",
    keyStrength: "Elite toe-crushing yorker execution at high pace",
    eraGeneration: "Modern Era",
    signatureMetric: "5 Wickets for 5 Runs in IPL Eliminator (2023)"
  },
  {
    name: "Matthew Hayden",
    country: "Australia",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,107",
    playingStyle: "Violent Left-arm Opener",
    keyStrength: "Charges bowlers, huge power, used Mongoose bat",
    eraGeneration: "Historical Legends",
    signatureMetric: "Orange Cap Winner 2009"
  },
  {
    name: "Michael Hussey",
    country: "Australia",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["CSK", "MI"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,977",
    playingStyle: "Perfect Left-hand Anchor",
    keyStrength: "Elite timing, beautiful cover drive, cover placement",
    eraGeneration: "Historical Legends",
    signatureMetric: "Mr. Cricket / Orange Cap 2013"
  },
  {
    name: "Muttiah Muralitharan",
    country: "Sri Lanka",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["CSK", "Kochi Tuskers", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "63",
    playingStyle: "Greatest Offspinner in History",
    keyStrength: "Fierce wrist-spin action offbreak & doosra",
    eraGeneration: "Historical Legends",
    signatureMetric: "800 Test Wickets / CSK Spin Wizard"
  },
  {
    name: "Kumar Sangakkara",
    country: "Sri Lanka",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["KXIP", "Deccan Chargers", "SRH"],
    captain: true,
    wicketkeeper: true,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,687",
    playingStyle: "Graceful Left-hand Anchor",
    keyStrength: "Elite cover drive and superb keeping reflexes",
    eraGeneration: "Historical Legends",
    signatureMetric: "Sri Lankan Legendary Wicketkeeper"
  },
  {
    name: "Brendon McCullum",
    country: "New Zealand",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["KKR", "CSK", "RCB", "GL", "Kochi Tuskers"],
    captain: true,
    wicketkeeper: true,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,880",
    playingStyle: "Uncompromising Power Opener",
    keyStrength: "Audacious scoops and clearing fields easily",
    eraGeneration: "Historical Legends",
    signatureMetric: "158* in Inaugural IPL Match (2008)"
  },
  {
    name: "Sunil Narine",
    country: "West Indies",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["KKR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 3,
    debutYear: 2012,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,450",
    playingStyle: "Mystery Spinner & Pinch Hitter",
    keyStrength: "Hard-to-read carrom ball & blazing powerplay hits",
    eraGeneration: "Historical Legends",
    signatureMetric: "Three-time IPL MVP (Most Valuable Player)"
  },
  {
    name: "Lendl Simmons",
    country: "West Indies",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium-fast",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 2,
    debutYear: 2014,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,079",
    playingStyle: "Reliable Opener",
    keyStrength: "Solid punch shots and strong cut shots",
    eraGeneration: "Historical Legends",
    signatureMetric: "Clutch MI Championship Opener"
  },
  {
    name: "Mitchell Johnson",
    country: "Australia",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast",
    teams: ["MI", "KXIP", "KKR"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 2,
    debutYear: 2013,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "140",
    playingStyle: "Fierce Left-arm Express Speed",
    keyStrength: "Violent left-arm swing and skiddy short-pitched bowling",
    eraGeneration: "Historical Legends",
    signatureMetric: "Defended 7 runs in Final Over of IPL 2017"
  },
  {
    name: "Eoin Morgan",
    country: "England",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["KKR", "SRH", "KXIP", "RCB"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 1,
    debutYear: 2010,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,455",
    playingStyle: "Cool-headed Middle-order Finisher",
    keyStrength: "Deft reverse sweeps and elegant aerial shots",
    eraGeneration: "Historical Legends",
    signatureMetric: "Led KKR to 2021 IPL Finals"
  }
];

// Deduplicate based on name
const playerNames = new Set(players.map(p => p.name));
let addedCount = 0;

evenMorePlayers.forEach(newPlayer => {
  if (!playerNames.has(newPlayer.name)) {
    players.push(newPlayer);
    playerNames.add(newPlayer.name);
    addedCount++;
  }
});

console.log(`Added ${addedCount} brand new unique players!`);
console.log(`Total database pool size now: ${players.length}`);

// Write back to players.json
fs.writeFileSync(playersFilePath, JSON.stringify(players, null, 2), 'utf8');
console.log("players.json updated successfully.");
