const fs = require('fs');
const path = require('path');

const playersFilePath = path.join(__dirname, '../data/players.json');

// Load existing players
let players = [];
if (fs.existsSync(playersFilePath)) {
  try {
    players = JSON.parse(fs.readFileSync(playersFilePath, 'utf8'));
  } catch (e) {
    console.error("Failed reading players.json", e);
  }
}

console.log("Original players.json size:", players.length);

const additionalPlayers = [
  {
    name: "Sai Sudharsan",
    country: "India",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["GT"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,034",
    playingStyle: "Elegant Accumulator",
    keyStrength: "Graceful Cover Drive & Spin Attack",
    eraGeneration: "Modern Generation",
    signatureMetric: "IPL Final 96 (2023)"
  },
  {
    name: "Shahrukh Khan",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["GT", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "520",
    playingStyle: "Power Finisher",
    keyStrength: "Brute Force Cleared Boundaries",
    eraGeneration: "Modern Era",
    signatureMetric: "Late Order Striker"
  },
  {
    name: "Mayank Yadav",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["LSG"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "10",
    playingStyle: "Raw Express Pace",
    keyStrength: "Consistent 155+ kmph Thunderbolt Pace",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Fastest ball of IPL 2024"
  },
  {
    name: "Harshit Rana",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["KKR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "45",
    playingStyle: "Aggressive Enforcer",
    keyStrength: "Fierce Bouncers & Searing Yorkers",
    eraGeneration: "Modern Era",
    signatureMetric: "Champion 2024 KKR Bowler"
  },
  {
    name: "Gerald Coetzee",
    country: "South Africa",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "30",
    playingStyle: "Express Attack",
    keyStrength: "Rabid Pace & Intimidating Bouncer",
    eraGeneration: "Modern Era",
    signatureMetric: "South African Speedster"
  },
  {
    name: "Jitesh Sharma",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["PBKS"],
    captain: true,
    wicketkeeper: true,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "730",
    playingStyle: "Attacking Finisher",
    keyStrength: "Fearless Hitting vs Pace from Ball One",
    eraGeneration: "Modern Generation",
    signatureMetric: "Vice Captain / Finisher"
  },
  {
    name: "Mitchell Santner",
    country: "New Zealand",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["CSK"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 3,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "140",
    playingStyle: "Economical Spinner",
    keyStrength: "Stifling Accuracy & Clever Drift",
    eraGeneration: "Modern Era",
    signatureMetric: "Three-Time Champion"
  },
  {
    name: "Shoaib Akhtar",
    country: "Pakistan",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["KKR"],
    captain: false,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "12",
    playingStyle: "Searing Raw Pace",
    keyStrength: "Unmatched 160kmph+ Raw Velocity",
    eraGeneration: "Inaugural Legends",
    signatureMetric: "4 Wickets on IPL debut (2008)"
  },
  {
    name: "Vaibhav Arora",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["KKR", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "15",
    playingStyle: "Swing Specialist",
    keyStrength: "Elite Powerplay Prodigious Swing",
    eraGeneration: "Modern Era",
    signatureMetric: "KKR Swing Champion"
  },
  {
    name: "Rahul Tewatia",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["GT", "RR", "DC", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2014,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "830",
    playingStyle: "Clutch Finisher",
    keyStrength: "Miraculous Death-over Hitting under Pressure",
    eraGeneration: "Modern Era",
    signatureMetric: "5 Sixes in an over (Cottrell)"
  },
  {
    name: "Harpreet Brar",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "210",
    playingStyle: "Tight Utility Bowler",
    keyStrength: "Extremely Economical middle-overs spell",
    eraGeneration: "Modern Era",
    signatureMetric: "Kohli-Maxwell-AB de Villiers Triple-Wicket Spell"
  },
  {
    name: "Matthew Wade",
    country: "Australia",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["GT", "DD"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2011,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "185",
    playingStyle: "Aggressive Keeper-Batsman",
    keyStrength: "Deft sweeps and lap shots",
    eraGeneration: "Modern Era",
    signatureMetric: "Australian T20 Champion"
  },
  {
    name: "Noor Ahmad",
    country: "Afghanistan",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm chinaman",
    teams: ["GT"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "15",
    playingStyle: "Mystery Chinaman",
    keyStrength: "Fast, deceptive googlies from a high release",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Afghan Mystery Spinner"
  },
  {
    name: "Vijay Shankar",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["GT", "SRH", "DC", "CSK"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2014,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,110",
    playingStyle: "Middle-order Strokeplayer",
    keyStrength: "Elegant driving and utility medium pace",
    eraGeneration: "Modern Generation",
    signatureMetric: "World Cup 3D Player"
  },
  {
    name: "Abhinav Manohar",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["GT"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "230",
    playingStyle: "Clean Power Hitter",
    keyStrength: "Brilliant striking against high spin",
    eraGeneration: "Modern Era",
    signatureMetric: "Hard-hitting Gujarat Finisher"
  },
  {
    name: "Chetan Sakariya",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["KKR", "DC", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "25",
    playingStyle: "Left-arm Swing Bowler",
    keyStrength: "Back-of-the-hand slower balls and back-of-length swing",
    eraGeneration: "Modern Era",
    signatureMetric: "Inspiring Rajasthan Debutant"
  },
  {
    name: "KS Bharat",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["KKR", "GT", "RCB", "DC"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2021,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "199",
    playingStyle: "Technical Anchor Wicketkeeper",
    keyStrength: "Superb keeping reflexes & clean pulls",
    eraGeneration: "Modern Era",
    signatureMetric: "Last-ball six vs DC for RCB (2021)"
  },
  {
    name: "Rahmanullah Gurbaz",
    country: "Afghanistan",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["KKR", "GT"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 2,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "280",
    playingStyle: "Explosive Opener",
    keyStrength: "Fearless aerial lofting in Powerplay",
    eraGeneration: "New Gen Rising",
    signatureMetric: "IPL Finalist Opener"
  },
  {
    name: "Suyash Sharma",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["KKR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "5",
    playingStyle: "Fast Leg Spinner",
    keyStrength: "Unconventional quick googly from high action",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Mystery Spinner Debutant"
  },
  {
    name: "Angkrish Raghuvanshi",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["KKR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "163",
    playingStyle: "Stylish Strokeplayer",
    keyStrength: "Elite square cuts and pick-up shots",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Fearless 54 on KKR Debut at 18"
  },
  {
    name: "Marcus Stoinis",
    country: "Australia",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["LSG", "DC", "RCB", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2016,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,730",
    playingStyle: "Power Hitter / Medium Pacer",
    keyStrength: "Clutch boundary clearing & death bowling options",
    eraGeneration: "Modern Generation",
    signatureMetric: "124* vs CSK in chase (2024)"
  },
  {
    name: "Nicholas Pooran",
    country: "West Indies",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["LSG", "SRH", "PBKS", "MI"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,680",
    playingStyle: "Explosive Finisher",
    keyStrength: "Unmatched swing speed and monstrous lofted drives",
    eraGeneration: "Modern Era",
    signatureMetric: "LSG Dynamic Finisher"
  },
  {
    name: "Devdutt Padikkal",
    country: "India",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["LSG", "RR", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2020,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,550",
    playingStyle: "Elegant Top-order Anchor",
    keyStrength: "Graceful driving and lofty straight sixes",
    eraGeneration: "Modern Era",
    signatureMetric: "IPL Century for RCB vs RR"
  },
  {
    name: "Ayush Badoni",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["LSG"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "580",
    playingStyle: "360-degree Innovative Finisher",
    keyStrength: "Scoop shots and smart field-piercing strokes",
    eraGeneration: "New Gen Rising",
    signatureMetric: "LSG Baby AB"
  },
  {
    name: "Krunal Pandya",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["LSG", "MI"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 3,
    debutYear: 2016,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,514",
    playingStyle: "Fierce Multi-utility Player",
    keyStrength: "Flatter, tight lines and flat-batted boundaries",
    eraGeneration: "Modern Era",
    signatureMetric: "Three-time MI champion"
  },
  {
    name: "Ravi Bishnoi",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["LSG", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2020,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "60",
    playingStyle: "Quick Legspinner",
    keyStrength: "Hard-to-read rapid googlies with high pace",
    eraGeneration: "Modern Era",
    signatureMetric: "Top T20 International Bowler"
  },
  {
    name: "Naveen-ul-Haq",
    country: "Afghanistan",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["LSG"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "10",
    playingStyle: "Deceptive Skiddy Bowler",
    keyStrength: "Elite slow cutters and aggressive bouncers",
    eraGeneration: "Modern Era",
    signatureMetric: "LSG Mango controversy match hero"
  },
  {
    name: "Yash Thakur",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["LSG"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "5",
    playingStyle: "Death-overs Yorker Specialist",
    keyStrength: "Fierce execution of outside-off yorkers",
    eraGeneration: "Modern Era",
    signatureMetric: "5-wicket haul vs GT (2024)"
  },
  {
    name: "Amit Mishra",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["LSG", "DC", "SRH", "Deccan Chargers"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "360",
    playingStyle: "Classical Loop Leg Spinner",
    keyStrength: "Stunning dip, classical legbreak, flight",
    eraGeneration: "Historical Legends",
    signatureMetric: "Three IPL Hat-tricks (Record)"
  },
  {
    name: "Deepak Hooda",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["LSG", "PBKS", "SRH", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2015,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,320",
    playingStyle: "Aggressive Middle-order Striker",
    keyStrength: "Great reach to loft spinners over long-on",
    eraGeneration: "Modern Era",
    signatureMetric: "India T20I Centurion"
  },
  {
    name: "Krishnappa Gowtham",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["LSG", "CSK", "PBKS", "RR", "MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "247",
    playingStyle: "Powerplay Offspinner & Hitter",
    keyStrength: "Fierce powerplay off-spin and brute sixes",
    eraGeneration: "Modern Era",
    signatureMetric: "Record 9.25 crore auction buy (CSK)"
  },
  {
    name: "Shivam Mavi",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["LSG", "GT", "KKR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "60",
    playingStyle: "Skiddy Pace Bowler",
    keyStrength: "Outswingers and high pace in early overs",
    eraGeneration: "Modern Era",
    signatureMetric: "U-19 World Cup star"
  },
  {
    name: "Piyush Chawla",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["MI", "CSK", "KKR", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 2,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "609",
    playingStyle: "Experienced Legspinner",
    keyStrength: "Excellent wrong-un and high spin experience",
    eraGeneration: "Historical Legends",
    signatureMetric: "2nd Highest Wicket Taker in IPL"
  },
  {
    name: "Shreyas Gopal",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["MI", "RR", "SRH"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2014,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "180",
    playingStyle: "Flat Leg Spinner",
    keyStrength: "Deceptive sliders and googly",
    eraGeneration: "Modern Era",
    signatureMetric: "IPL Hat-trick vs RCB (Kohli-AB-Stoinis)"
  },
  {
    name: "Nehal Wadhera",
    country: "India",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "350",
    playingStyle: "Flamboyant Left-hander",
    keyStrength: "Clean lofted cover drives and powerful sweep shots",
    eraGeneration: "New Gen Rising",
    signatureMetric: "MI Middle order anchor"
  },
  {
    name: "Romario Shepherd",
    country: "West Indies",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["MI", "LSG", "SRH"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "150",
    playingStyle: "Destructive lower order finisher",
    keyStrength: "Extreme muscle-power hitting against fast bowlers",
    eraGeneration: "Modern Era",
    signatureMetric: "32 runs off an over vs Anrich Nortje (2024)"
  },
  {
    name: "Mohammad Nabi",
    country: "Afghanistan",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["MI", "SRH", "KKR"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "215",
    playingStyle: "Cool-headed Veteran Spinner",
    keyStrength: "Flat tight powerplay lines and straight sixes",
    eraGeneration: "Modern Era",
    signatureMetric: "The President of Afghan Cricket"
  },
  {
    name: "Naman Dhir",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "140",
    playingStyle: "Fearless Power Hitter",
    keyStrength: "Aggressive lofted straight drive",
    eraGeneration: "New Gen Rising",
    signatureMetric: "MI Emerging dynamic all-rounder"
  },
  {
    name: "Sam Curran",
    country: "England",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["PBKS", "CSK"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "830",
    playingStyle: "Clever Swing Bowling All-rounder",
    keyStrength: "Prodigious swing, clever cutters, clutch lower-order runs",
    eraGeneration: "Modern Generation",
    signatureMetric: "Most Expensive IPL Auction Buy (18.5 Crore)"
  },
  {
    name: "Liam Livingstone",
    country: "England",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["PBKS", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "930",
    playingStyle: "Monstrous Power Hitter / Spin Options",
    keyStrength: "Hitting some of the longest sixes in cricket history",
    eraGeneration: "Modern Era",
    signatureMetric: "117m Sixer in IPL 2022"
  },
  {
    name: "Kagiso Rabada",
    country: "South Africa",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["PBKS", "DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "186",
    playingStyle: "Violent Express Bowler",
    keyStrength: "Fierce toe-crushing yorkers and high bounce",
    eraGeneration: "Modern Generation",
    signatureMetric: "Purple Cap Winner"
  },
  {
    name: "Arshdeep Singh",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "30",
    playingStyle: "Elite Left-arm Death Bowler",
    keyStrength: "Searing death-overs outside-off yorkers and early swing",
    eraGeneration: "Modern Era",
    signatureMetric: "Broke middle stumps in IPL"
  },
  {
    name: "Harshal Patel",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["PBKS", "RCB", "DC"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2012,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "240",
    playingStyle: "Cutters & Slow-ball Wizard",
    keyStrength: "Deceptive dipping slower balls & knuckleballs",
    eraGeneration: "Modern Era",
    signatureMetric: "Record 32 Wickets in a single season (Purple Cap)"
  },
  {
    name: "Sikandar Raza",
    country: "Zimbabwe",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "140",
    playingStyle: "Clutch Spin-bowling Finisher",
    keyStrength: "Mystery spin options and lofted boundary strokes",
    eraGeneration: "Modern Era",
    signatureMetric: "Zimbabwe Legendary All-rounder"
  },
  {
    name: "Ashutosh Sharma",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "189",
    playingStyle: "Fearless Sweeper Finisher",
    keyStrength: "Audacious sweep shots against express pace",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Swept Jasprit Bumrah for six"
  },
  {
    name: "Shashank Singh",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["PBKS", "SRH", "DC", "RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "354",
    playingStyle: "Unshakeable Power Finisher",
    keyStrength: "Cool-headed lofted drives over covers under pressure",
    eraGeneration: "Modern Era",
    signatureMetric: "Accidental purchase turned match winner"
  },
  {
    name: "Avesh Khan",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RR", "LSG", "DC", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "45",
    playingStyle: "Hard Length Speedster",
    keyStrength: "Seam-up hard length bowling and wide yorkers",
    eraGeneration: "Modern Era",
    signatureMetric: "Aggressive wicket celebrations"
  },
  {
    name: "Sandeep Sharma",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["RR", "SRH", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2013,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "30",
    playingStyle: "New-ball / Death-overs Swing Maestro",
    keyStrength: "Outstanding outswing and skiddy death-overs knuckleballs",
    eraGeneration: "Modern Generation",
    signatureMetric: "Dismissed Virat Kohli 7 times"
  },
  {
    name: "Dhruv Jurel",
    country: "India",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["RR"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "300",
    playingStyle: "Composed Middle-order Striker",
    keyStrength: "Elite placement, superb spin defense, and fast keeping",
    eraGeneration: "New Gen Rising",
    signatureMetric: "Salute celebration"
  },
  {
    name: "Riyan Parag",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "920",
    playingStyle: "Elite Lofted Hitter",
    keyStrength: "Monstrous inside-out drives & flat spin hitting",
    eraGeneration: "Modern Generation",
    signatureMetric: "Assam Bihu dance celebration"
  },
  {
    name: "Shimron Hetmyer",
    country: "West Indies",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "None",
    teams: ["RR", "DC", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2019,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,220",
    playingStyle: "Fearless Left-arm Finisher",
    keyStrength: "Fierce hitting against express pace and wide boundaries",
    eraGeneration: "Modern Era",
    signatureMetric: "West Indian Power Finisher"
  },
  {
    name: "Nandre Burger",
    country: "South Africa",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast",
    teams: ["RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "10",
    playingStyle: "Express Left-arm Speed",
    keyStrength: "Searing high bounce and left-arm swing at 145kmph+",
    eraGeneration: "New Gen Rising",
    signatureMetric: "South African Left-arm Star"
  },
  {
    name: "Keshav Maharaj",
    country: "South Africa",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["RR"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "15",
    playingStyle: "Traditional Left-arm Spinner",
    keyStrength: "Flight, drift, and immense control on turning tracks",
    eraGeneration: "Modern Era",
    signatureMetric: "Devout Indian Heritage Proteas Spinner"
  },
  {
    name: "Yash Dayal",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["RCB", "GT"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2022,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "10",
    playingStyle: "Left-arm swing bowler",
    keyStrength: "Excellent new-ball swing and skiddy bouncers",
    eraGeneration: "Modern Generation",
    signatureMetric: "RCB Playoffs Hero (2024)"
  },
  {
    name: "Swapnil Singh",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["RCB", "LSG", "KXIP", "MI"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "120",
    playingStyle: "Veteran Utility Spinner",
    keyStrength: "Fired-in economical left-arm spin & handy sixes",
    eraGeneration: "Historical Legends",
    signatureMetric: "RCB late-season turnaround star"
  },
  {
    name: "Will Jacks",
    country: "England",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2024,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "230",
    playingStyle: "Violent Boundary Striker",
    keyStrength: "Savage power against spin and off-spin support",
    eraGeneration: "New Gen Rising",
    signatureMetric: "41-ball Century for RCB vs GT"
  },
  {
    name: "Lockie Ferguson",
    country: "New Zealand",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast",
    teams: ["RCB", "KKR", "GT", "RPS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 1,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "42",
    playingStyle: "Express Speedster",
    keyStrength: "Consistent 150kmph+ blistering pace & toe-crushers",
    eraGeneration: "Modern Era",
    signatureMetric: "Super Over Winner for KKR"
  },
  {
    name: "Reece Topley",
    country: "England",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "5",
    playingStyle: "Tall Left-arm Swing Bowler",
    keyStrength: "Fierce bounce from 6ft 7in height & inward swing",
    eraGeneration: "Modern Era",
    signatureMetric: "English Left-arm Giant"
  },
  {
    name: "Bhuvneshwar Kumar",
    country: "India",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["SRH", "PWI"],
    captain: true,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 1,
    debutYear: 2009,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "295",
    playingStyle: "Master Swing Bowler",
    keyStrength: "Impeccable control, massive outswing & inswing early on",
    eraGeneration: "Historical Legends",
    signatureMetric: "Two-time Purple Cap Winner"
  },
  {
    name: "Heinrich Klaasen",
    country: "South Africa",
    role: "Wicketkeeper",
    battingStyle: "Right-hand bat",
    bowlingStyle: "None",
    teams: ["SRH", "RCB", "RR"],
    captain: false,
    wicketkeeper: true,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "950",
    playingStyle: "Savage Spin Destructor",
    keyStrength: "Monstrous backfoot pull shots and pull-sixes against spin",
    eraGeneration: "Modern Generation",
    signatureMetric: "Safest Wicketkeeper-Batsman in T20"
  },
  {
    name: "Travis Head",
    country: "Australia",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["SRH", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: true,
    retired: false,
    iplTitles: 0,
    debutYear: 2016,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "780",
    playingStyle: "Fearless Ultrafast Opener",
    keyStrength: "Devastating cuts and flat-batted drives in Powerplay",
    eraGeneration: "Modern Generation",
    signatureMetric: "IPL 39-ball Century vs RCB (2024)"
  },
  {
    name: "Abhishek Sharma",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["SRH", "DD"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2018,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,120",
    playingStyle: "Ultrafast Blaster / Spin Utility",
    keyStrength: "Fierce lofted straight shots & flat spinner bashing",
    eraGeneration: "Modern Era",
    signatureMetric: "Most Sixes by an Indian in IPL 2024"
  },
  {
    name: "Nitish Kumar Reddy",
    country: "India",
    role: "All-rounder",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm fast-medium",
    teams: ["SRH"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2023,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "303",
    playingStyle: "Dynamic Pace-bowling All-rounder",
    keyStrength: "Assertive pull shots and skiddy medium-pace spells",
    eraGeneration: "New Gen Rising",
    signatureMetric: "IPL Emerging Player of the Year 2024"
  },
  {
    name: "T Natarajan",
    country: "India",
    role: "Bowler",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm fast-medium",
    teams: ["SRH", "PBKS"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2017,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "12",
    playingStyle: "Death-overs Yorker King",
    keyStrength: "Unrivaled execution of late dipping yorkers",
    eraGeneration: "Modern Era",
    signatureMetric: "Left-arm Yorker Specialist"
  },
  {
    name: "Shahbaz Ahmed",
    country: "India",
    role: "All-rounder",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Left-arm orthodox",
    teams: ["SRH", "RCB"],
    captain: false,
    wicketkeeper: false,
    active: true,
    overseas: false,
    retired: false,
    iplTitles: 0,
    debutYear: 2020,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "420",
    playingStyle: "Gritty Utility All-rounder",
    keyStrength: "Clever flat-angled left-arm spin and flexible batting",
    eraGeneration: "Modern Era",
    signatureMetric: "SRH Finalist Matchwinner"
  },
  {
    name: "Adam Gilchrist",
    country: "Australia",
    role: "Wicketkeeper",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["Deccan Chargers", "KXIP"],
    captain: true,
    wicketkeeper: true,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,069",
    playingStyle: "Fierce Wicketkeeper-Opener",
    keyStrength: "Savage pull shots and dynamic leadership",
    eraGeneration: "Historical Legends",
    signatureMetric: "Led Deccan Chargers to Title (2009)"
  },
  {
    name: "Shane Warne",
    country: "Australia",
    role: "Bowler",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm legbreak",
    teams: ["RR"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: true,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1628157582853-a796fa650a6a?q=80&w=600&auto=format&fit=crop",
    careerRuns: "198",
    playingStyle: "Masterful Tactical Legspinner",
    keyStrength: "Prodigious legbreak turn, smart setups, genius captaincy",
    eraGeneration: "Historical Legends",
    signatureMetric: "Led Underdog RR to Inaugural Title (2008)"
  },
  {
    name: "Sourav Ganguly",
    country: "India",
    role: "Batsman",
    battingStyle: "Left-hand bat",
    bowlingStyle: "Right-arm medium",
    teams: ["KKR", "PWI"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=600&auto=format&fit=crop",
    careerRuns: "1,349",
    playingStyle: "Royal Left-hand Playmaker",
    keyStrength: "Elite off-side drives and stepping out to spin",
    eraGeneration: "Historical Legends",
    signatureMetric: "Dada / Legend Captain"
  },
  {
    name: "Rahul Dravid",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["RCB", "RR"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 0,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1540747737956-37872404a821?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,174",
    playingStyle: "Impenetrable Anchor",
    keyStrength: "Impeccable classical defense & backfoot punch",
    eraGeneration: "Historical Legends",
    signatureMetric: "The Wall"
  },
  {
    name: "Sachin Tendulkar",
    country: "India",
    role: "Batsman",
    battingStyle: "Right-hand bat",
    bowlingStyle: "Right-arm offbreak",
    teams: ["MI"],
    captain: true,
    wicketkeeper: false,
    active: false,
    overseas: false,
    retired: true,
    iplTitles: 1,
    debutYear: 2008,
    imageUrl: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=600&auto=format&fit=crop",
    careerRuns: "2,334",
    playingStyle: "Flawless Classical Batsman",
    keyStrength: "Perfect straight drive and paddle sweeps",
    eraGeneration: "Historical Legends",
    signatureMetric: "Orange Cap Winner 2010"
  }
];

// Deduplicate based on name
const playerNames = new Set(players.map(p => p.name));
let addedCount = 0;

additionalPlayers.forEach(newPlayer => {
  if (!playerNames.has(newPlayer.name)) {
    players.push(newPlayer);
    playerNames.add(newPlayer.name);
    addedCount++;
  }
});

console.log(`Added ${addedCount} brand new unique players!`);
console.log(`Total database pool size now: ${players.length}`);

// Write back to players.json
fs.writeFileSync(playersFilePath, JSON.stringify(players, null, 2), 'utf8');
console.log("players.json updated successfully.");
