const fs = require('fs');
const path = require('path');

const playersFilePath = path.join(__dirname, '../data/players.json');

// Load existing players
let existingPlayers = [];
if (fs.existsSync(playersFilePath)) {
  try {
    existingPlayers = JSON.parse(fs.readFileSync(playersFilePath, 'utf8'));
  } catch (e) {
    console.error("Failed reading base JSON", e);
  }
}

// Add proper missing fields to existing players based on name mappings
const knownTitles = {
  "Rohit Sharma": 6, "MS Dhoni": 5, "Ambati Rayudu": 6, "Hardik Pandya": 5, "Kieron Pollard": 5,
  "Jasprit Bumrah": 5, "Suresh Raina": 4, "Ravindra Jadeja": 4, "Lasith Malinga": 4, "Sunil Narine": 3,
  "Andre Russell": 2, "Gautam Gambhir": 2, "Yuvraj Singh": 2, "Shane Watson": 2, "Dwayne Bravo": 3,
  "Ravichandran Ashwin": 2, "Faf du Plessis": 2, "Ruturaj Gaikwad": 1, "Shubman Gill": 1, "Rashid Khan": 1,
  "Axar Patel": 0, "Virat Kohli": 0, "AB de Villiers": 0, "Chris Gayle": 0, "KL Rahul": 0
};

const knownDebut = {
  "Virat Kohli": 2008, "MS Dhoni": 2008, "Rohit Sharma": 2008, "Suresh Raina": 2008, "Gautam Gambhir": 2008,
  "Dinesh Karthik": 2008, "Shikhar Dhawan": 2008, "Robin Uthappa": 2008, "AB de Villiers": 2008, "Chris Gayle": 2009,
  "Kieron Pollard": 2010, "Ravindra Jadeja": 2008, "Sunil Narine": 2012, "Andre Russell": 2012, "Lasith Malinga": 2009,
  "Jasprit Bumrah": 2013, "Hardik Pandya": 2015, "Rashid Khan": 2017, "Shubman Gill": 2018, "Ruturaj Gaikwad": 2020,
  "Yashasvi Jaiswal": 2020, "Rinku Singh": 2018, "Tilak Varma": 2022, "Heinrich Klaasen": 2018, "Pat Cummins": 2014
};

existingPlayers = existingPlayers.map(p => {
  const active = p.active !== undefined ? p.active : true;
  const retired = p.retired !== undefined ? p.retired : !active;
  const titles = knownTitles[p.name] !== undefined ? knownTitles[p.name] : (p.teams && (p.teams.includes("CSK") || p.teams.includes("MI")) ? 1 : 0);
  const debut = knownDebut[p.name] !== undefined ? knownDebut[p.name] : (retired ? 2008 : 2016);

  return {
    ...p,
    retired,
    iplTitles: titles,
    debutYear: debut,
    active: active // Keep synced
  };
});

// Master Array of 150 Additional Distinct Players (Historical & Modern)
const extraPlayers = [
  // Legends & Retired
  { name: "Sachin Tendulkar", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 1, debutYear: 2008, keyStrength: "Straight Drive" },
  { name: "Rahul Dravid", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB", "RR"], captain: true, wicketkeeper: true, active: false, retired: true, overseas: false, iplTitles: 0, debutYear: 2008, keyStrength: "Defense" },
  { name: "Sourav Ganguly", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR", "PWI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 0, debutYear: 2008, keyStrength: "Off Side Play" },
  { name: "VVS Laxman", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["Deccan Chargers", "Kochi Tuskers"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 1, debutYear: 2008, keyStrength: "Wristy Flicks" },
  { name: "Jacques Kallis", country: "South Africa", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RCB", "KKR"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008, keyStrength: "Technique" },
  { name: "Adam Gilchrist", country: "Australia", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["Deccan Chargers", "KXIP"], captain: true, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008, keyStrength: "Cut Shots" },
  { name: "Shane Warne", country: "Australia", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RR"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008, keyStrength: "Leg Spin" },
  { name: "Matthew Hayden", country: "Australia", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008, keyStrength: "Mongoose Bat Power" },
  { name: "Michael Hussey", country: "Australia", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK", "MI"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008, keyStrength: "Consistency" },
  { name: "Dwayne Bravo", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK", "MI", "GL"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 3, debutYear: 2008, keyStrength: "Slower Balls" },
  { name: "Shane Watson", country: "Australia", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "RCB", "CSK"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008, keyStrength: "Power Hitting" },
  { name: "Brendon McCullum", country: "New Zealand", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR", "CSK", "RCB", "GL", "Kochi Tuskers"], captain: true, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008, keyStrength: "Aggression" },
  { name: "Zaheer Khan", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["MI", "RCB", "DD"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 0, debutYear: 2008, keyStrength: "Swing & Knuckleball" },
  { name: "Harbhajan Singh", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI", "CSK", "KKR"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 4, debutYear: 2008, keyStrength: "Doosra" },
  { name: "Anil Kumble", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RCB"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 0, debutYear: 2008, keyStrength: "Top Spin & Bounce" },
  { name: "Yusuf Pathan", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RR", "KKR", "SRH"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 3, debutYear: 2008, keyStrength: "Massive Sixes" },
  { name: "Robin Uthappa", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR", "CSK", "RCB", "MI", "RR", "PWI"], captain: false, wicketkeeper: true, active: false, retired: true, overseas: false, iplTitles: 2, debutYear: 2008, keyStrength: "Walking Shot" },
  { name: "Piyush Chawla", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["MI", "CSK", "KKR", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2008, keyStrength: "Wrong-un" },
  { name: "Ambati Rayudu", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI", "CSK"], captain: false, wicketkeeper: true, active: false, retired: true, overseas: false, iplTitles: 6, debutYear: 2010, keyStrength: "Spin Attack" },
  { name: "Shaun Marsh", country: "Australia", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KXIP"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008, keyStrength: "Orange Cap 2008" },
  { name: "Murali Vijay", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["CSK", "KXIP", "DD"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 2, debutYear: 2009, keyStrength: "Loft" },
  { name: "Deepak Chahar", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["CSK", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 3, debutYear: 2016, keyStrength: "Early Swing" },
  { name: "Shardul Thakur", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["CSK", "KKR", "DC", "PBKS", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2015, keyStrength: "Golden Arm Wickets" },
  { name: "Kagiso Rabada", country: "South Africa", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast", teams: ["PBKS", "DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2017, keyStrength: "Raw Pace" },
  { name: "David Miller", country: "South Africa", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["GT", "PBKS", "RR"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2012, keyStrength: "Miller the Killer Finish" },
  { name: "Marcus Stoinis", country: "Australia", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["LSG", "DC", "RCB", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2016, keyStrength: "Muscular Hitting" },
  { name: "Nicholas Pooran", country: "West Indies", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["LSG", "SRH", "PBKS", "MI"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2019, keyStrength: "Clean Ball Striking" },
  { name: "Shimron Hetmyer", country: "West Indies", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "None", teams: ["RR", "DC", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2019, keyStrength: "Death Overs Finish" },
  { name: "Jofra Archer", country: "England", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["MI", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2018, keyStrength: "Extreme Pace & Bounce" },
  { name: "Sam Curran", country: "England", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["PBKS", "CSK"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2019, keyStrength: "Swing & Utility" },
  { name: "Ben Stokes", country: "England", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["CSK", "RR", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2017, keyStrength: "Clutch Impact" },
  { name: "Cameron Green", country: "Australia", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RCB", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023, keyStrength: "Tall Driving & Bounce" },
  { name: "Suryakumar Yadav", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["MI", "KKR"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 4, debutYear: 2012, keyStrength: "360 Shots / Supla Shot" },
  { name: "Ishan Kishan", country: "India", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "None", teams: ["MI", "GL"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2016, keyStrength: "Fearless Pulls" },
  { name: "Tilak Varma", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2022, keyStrength: "Wristy Aesthetics" },
  { name: "Varun Chakravarthy", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["KKR", "KXIP"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2019, keyStrength: "Mystery Spin" },
  { name: "Krunal Pandya", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["LSG", "MI"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 3, debutYear: 2016, keyStrength: "Tight Accuracy" },
  { name: "Arshdeep Singh", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2019, keyStrength: "Death Yorkers" },
  { name: "Dinesh Karthik", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB", "KKR", "MI", "GL", "PWI", "DD", "PBKS"], captain: true, wicketkeeper: true, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2008, keyStrength: "Clutch Finisher" },
  { name: "Ravichandran Ashwin", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RR", "DC", "PBKS", "CSK", "RPS"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2009, keyStrength: "Carrom Ball" },
  { name: "Ajinkya Rahane", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK", "RR", "DC", "MI", "KKR", "RPS"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2008, keyStrength: "Timing" },
  { name: "Mitchell Marsh", country: "Australia", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["DC", "SRH", "PWI", "Deccan Chargers"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2010, keyStrength: "Brute Force" },
  { name: "Ishant Sharma", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["DC", "SRH", "KKR", "PBKS", "RPS", "Deccan Chargers"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2008, keyStrength: "Bounce & Hard Lengths" },
  { name: "Umesh Yadav", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["GT", "KKR", "RCB", "DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2010, keyStrength: "Outswing & Pace" },
  { name: "Mohit Sharma", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["GT", "CSK", "PBKS", "DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2013, keyStrength: "Back-of-hand Slower Balls" },
  { name: "Sandeep Sharma", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "SRH", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2013, keyStrength: "Early Swing & Knuckleball" },
  { name: "Khaleel Ahmed", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["DC", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2018, keyStrength: "Swing" },
  { name: "Kuldeep Yadav", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm chinaman", teams: ["DC", "KKR", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2016, keyStrength: "Chinaman Spin" },
  { name: "Deepak Hooda", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["LSG", "PBKS", "SRH", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2015, keyStrength: "Lofted Shots" },
  { name: "Venkatesh Iyer", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2021, keyStrength: "Driving" },
  { name: "Devdutt Padikkal", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["LSG", "RR", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2020, keyStrength: "Elegant Covers" },
  { name: "Prithvi Shaw", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2018, keyStrength: "Backfoot Punch" },
  { name: "Sai Sudharsan", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["GT"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2022, keyStrength: "Graceful Accumulation" },
  { name: "Rajat Patidar", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2021, keyStrength: "Elite Ball Striking vs Spin" },
  { name: "Sanvir Singh", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2023, keyStrength: "Pinch Hitting" },
  { name: "Mayank Yadav", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["LSG"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2024, keyStrength: "155kph+ Heat" },
  { name: "Harshit Rana", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2023, keyStrength: "Bouncers & Aggression" },
  { name: "Tushar Deshpande", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["CSK", "DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2020, keyStrength: "Pace & Swing" },
  { name: "Matheesha Pathirana", country: "Sri Lanka", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2022, keyStrength: "Malinga-like Slinging Death Overs" },
  { name: "Maheesh Theekshana", country: "Sri Lanka", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2022, keyStrength: "Carrom Ball" },
  { name: "Mustafizur Rahman", country: "Bangladesh", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["CSK", "DC", "RR", "SRH", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2016, keyStrength: "Cutters" },
  { name: "Nuwan Thushara", country: "Sri Lanka", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024, keyStrength: "Slinging Yorkers" },
  { name: "Rovman Powell", country: "West Indies", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["RR", "DC", "KKR"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022, keyStrength: "Raw Muscular Power" },
  { name: "Aiden Markram", country: "South Africa", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["SRH", "PBKS"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021, keyStrength: "Cover Drive" },
  { name: "Marco Jansen", country: "South Africa", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast", teams: ["SRH", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021, keyStrength: "Tall Bounce & Swing" },
  { name: "Tristan Stubbs", country: "South Africa", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["DC", "MI"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022, keyStrength: "Innovation & Power" },
  { name: "Jake Fraser-McGurk", country: "Australia", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024, keyStrength: "Fast Hands Destructive Hitting" },
  { name: "Phil Salt", country: "England", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["KKR", "DC"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2023, keyStrength: "Fearless Aggression" },
  { name: "Will Jacks", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024, keyStrength: "Violent Spin Hitting" },
  { name: "Liam Livingstone", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["PBKS", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2019, keyStrength: "Monster Sixes" },
  { name: "Jonny Bairstow", country: "England", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["PBKS", "SRH"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2019, keyStrength: "Aggressive Opener" },
  { name: "Jos Buttler", country: "England", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["RR", "MI"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2016, keyStrength: "Scoop" },
  { name: "Trent Boult", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast", teams: ["RR", "MI", "DC", "KKR", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2015, keyStrength: "Powerplay Swing" },
  { name: "Mitchell Santner", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 3, debutYear: 2019, keyStrength: "Control & Accuracy" },
  { name: "Rachin Ravindra", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024, keyStrength: "Elegant Clean Hitting" },
  { name: "Daryl Mitchell", country: "New Zealand", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["CSK", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022, keyStrength: "Down the ground Power" },
  { name: "Kane Williamson", country: "New Zealand", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["GT", "SRH"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2015, keyStrength: "Technical Anchor" },
  { name: "Glenn Phillips", country: "New Zealand", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["SRH", "RR"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021, keyStrength: "Dynamic Versatility" },
  { name: "Lockie Ferguson", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["RCB", "KKR", "GT", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2017, keyStrength: "150kph+ Heat" },
  { name: "Tim Southee", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["KKR", "RCB", "MI", "CSK", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2011, keyStrength: "Outswingers" },
  { name: "Mohammad Nabi", country: "Afghanistan", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI", "SRH", "KKR"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2017, keyStrength: "Tidy Accuracy & Power" },
  { name: "Noor Ahmad", country: "Afghanistan", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm chinaman", teams: ["GT"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023, keyStrength: "Fast Wrist Spin" },
  { name: "Azmatullah Omarzai", country: "Afghanistan", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["GT"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024, keyStrength: "New Ball Swing" },
  { name: "Wanindu Hasaranga", country: "Sri Lanka", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["SRH", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021, keyStrength: "Deceptive Googly" },
  { name: "Mohammad Rizwan", country: "Pakistan", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: [], captain: false, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Shoaib Akhtar", country: "Pakistan", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008, keyStrength: "Raw Pace" },
  { name: "Sohail Tanvir", country: "Pakistan", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["RR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008, keyStrength: "Wrong Foot Inswing" },
  { name: "Shane Bond", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2010 },
  { name: "Shaun Tait", country: "Australia", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["RR", "KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2010 },
  { name: "Mitchell Johnson", country: "Australia", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast", teams: ["MI", "KXIP", "KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2013 },
  { name: "Ryan Harris", country: "Australia", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["Deccan Chargers", "KXIP"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2009 },
  { name: "Adam Zampa", country: "Australia", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RR", "RCB", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2016 },
  { name: "Marcus Harris", country: "Australia", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "None", teams: [], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2015 },
  { name: "Steve Smith", country: "Australia", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["DC", "RR", "RPS", "RCB", "PWI", "Kochi Tuskers"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2012 },
  { name: "David Hussey", country: "Australia", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KKR", "KXIP", "CSK"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "George Bailey", country: "Australia", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["KXIP", "CSK", "RPS"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2009 },
  { name: "Chris Morris", country: "South Africa", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "RCB", "DC", "CSK"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2013 },
  { name: "Imran Tahir", country: "South Africa", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["CSK", "RPS", "DD"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2014 },
  { name: "JP Duminy", country: "South Africa", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI", "DC", "SRH", "Deccan Chargers"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2009 },
  { name: "Albie Morkel", country: "South Africa", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["CSK", "RCB", "DD", "RPS"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008 },
  { name: "Morne Morkel", country: "South Africa", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast", teams: ["KKR", "DD", "RR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2009 },
  { name: "Dale Steyn", country: "South Africa", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["RCB", "SRH", "GL", "Deccan Chargers"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Wayne Parnell", country: "South Africa", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["RCB", "PWI", "DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2011 },
  { name: "Hashim Amla", country: "South Africa", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["KXIP"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2016 },
  { name: "Quinton de Kock", country: "South Africa", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "None", teams: ["LSG", "MI", "RCB", "SRH", "DD"], captain: true, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2013 },
  { name: "Lungi Ngidi", country: "South Africa", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["DC", "CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2018 },
  { name: "Faf du Plessis", country: "South Africa", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RCB", "CSK", "RPS"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2012 },
  { name: "Rilee Rossouw", country: "South Africa", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["PBKS", "DC", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2014 },
  { name: "Geraud Coetzee", country: "South Africa", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024 },
  { name: "Nandre Burger", country: "South Africa", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast", teams: ["RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024 },
  { name: "Kieron Pollard", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["MI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 5, debutYear: 2010 },
  { name: "Chris Gayle", country: "West Indies", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB", "PBKS", "KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Dwayne Smith", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["MI", "CSK", "GL", "Deccan Chargers"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008 },
  { name: "Darren Sammy", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["SRH", "RCB", "KXIP"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2013 },
  { name: "Marlon Samuels", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["PWI", "DD"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2012 },
  { name: "Lendl Simmons", country: "West Indies", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["MI"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2014 },
  { name: "Jason Holder", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "LSG", "SRH", "KKR", "CSK"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2013 },
  { name: "Alzarri Joseph", country: "West Indies", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["RCB", "GT", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2019 },
  { name: "Roston Chase", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021 },
  { name: "Romario Shepherd", country: "West Indies", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["MI", "LSG", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022 },
  { name: "Shai Hope", country: "West Indies", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["DC"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024 },
  { name: "Eoin Morgan", country: "England", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR", "SRH", "KXIP", "RCB"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2010 },
  { name: "Kevin Pietersen", country: "England", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB", "DD", "RPS", "Deccan Chargers"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Paul Collingwood", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["DD", "RR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2010 },
  { name: "Andrew Flintoff", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["CSK"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Liam Plunkett", country: "England", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["DD"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2018 },
  { name: "Jason Roy", country: "England", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["KKR", "SRH", "DC", "GL"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2017 },
  { name: "Mark Wood", country: "England", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["LSG", "CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2018 },
  { name: "Tom Curran", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RCB", "DC", "RR", "KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2018 },
  { name: "Chris Woakes", country: "England", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["PBKS", "DC", "RCB", "KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2017 },
  { name: "Harry Brook", country: "England", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["DC", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023 },
  { name: "Adil Rashid", country: "England", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["SRH", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2021 },
  { name: "Sanath Jayasuriya", country: "Sri Lanka", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["MI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Kumar Sangakkara", country: "Sri Lanka", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KXIP", "Deccan Chargers", "SRH"], captain: true, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Mahela Jayawardene", country: "Sri Lanka", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["KXIP", "Kochi Tuskers", "DD"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Muttiah Muralitharan", country: "Sri Lanka", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["CSK", "Kochi Tuskers", "RCB"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008 },
  { name: "Angelo Mathews", country: "Sri Lanka", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["KKR", "PWI", "DD"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Thisara Perera", country: "Sri Lanka", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["CSK", "Kochi Tuskers", "MI", "SRH", "KXIP", "RPS"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2010 },
  { name: "Chaminda Vaas", country: "Sri Lanka", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["Deccan Chargers"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008 },
  { name: "Mujeeb Ur Rahman", country: "Afghanistan", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KKR", "SRH", "KXIP"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2018 },
  { name: "Naveen-ul-Haq", country: "Afghanistan", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["LSG"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023 },
  { name: "Fazalhaq Farooqi", country: "Afghanistan", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022 },
  { name: "Shakib Al Hasan", country: "Bangladesh", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["KKR", "SRH"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 2, debutYear: 2011 },
  { name: "Mashrafe Mortaza", country: "Bangladesh", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Liton Das", country: "Bangladesh", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["KKR"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023 },
  { name: "Taskin Ahmed", country: "Bangladesh", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast", teams: [], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2024 },
  { name: "Ryan ten Doeschate", country: "Netherlands", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium-fast", teams: ["KKR"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2011 },
  { name: "Sandeep Lamichhane", country: "Nepal", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2018 },
  { name: "Josh Little", country: "Ireland", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["GT"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023 },
  { name: "Sikandar Raza", country: "Zimbabwe", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2023 },
  { name: "Brendon Taylor", country: "Zimbabwe", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["SRH"], captain: false, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2014 },
  { name: "Tatenda Taibu", country: "Zimbabwe", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["KKR"], captain: false, wicketkeeper: true, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Dirk Nannes", country: "Australia", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast", teams: ["DD", "RCB", "CSK"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2009 },
  { name: "Roelof van der Merwe", country: "Netherlands", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["RCB", "DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Graeme Smith", country: "South Africa", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RR", "PWI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008 },
  { name: "Johan Botha", country: "South Africa", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RR", "KKR", "DD"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Richard Levi", country: "South Africa", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["MI"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2012 },
  { name: "Robin Peterson", country: "South Africa", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["MI", "KXIP"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2012 },
  { name: "Hardus Viljoen", country: "South Africa", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2019 },
  { name: "Ross Taylor", country: "New Zealand", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RCB", "RR", "DD", "PWI"], captain: true, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2008 },
  { name: "Jesse Ryder", country: "New Zealand", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["RCB", "PWI", "DD"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 0, debutYear: 2009 },
  { name: "Scott Styris", country: "New Zealand", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["Deccan Chargers", "CSK"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 2, debutYear: 2008 },
  { name: "Jacob Oram", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK", "RR", "MI"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2008 },
  { name: "James Franklin", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm medium-fast", teams: ["MI"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2011 },
  { name: "Corey Anderson", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["MI", "DD", "RCB"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: true, iplTitles: 1, debutYear: 2014 },
  { name: "Colin de Grandhomme", country: "New Zealand", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RCB", "KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2017 },
  { name: "Jimmy Neesham", country: "New Zealand", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "MI", "KXIP", "DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2014 },
  { name: "Adam Milne", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["CSK", "MI", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2016 },
  { name: "Kyle Jamieson", country: "New Zealand", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["CSK", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 1, debutYear: 2021 },
  { name: "Finn Allen", country: "New Zealand", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: true, iplTitles: 0, debutYear: 2022 },
  // Additional Batch of 40 Domestic Indian Stars
  { name: "Manish Pandey", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KKR", "RCB", "SRH", "LSG", "DC", "PWI"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2008, keyStrength: "First Indian Centurion" },
  { name: "Mayank Agarwal", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["SRH", "PBKS", "RCB", "DC", "RPS"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2011, keyStrength: "Inside out drives" },
  { name: "Wriddhiman Saha", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["GT", "SRH", "PBKS", "CSK", "KKR"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2008, keyStrength: "World-class Glovework" },
  { name: "Parthiv Patel", country: "India", role: "Wicketkeeper", battingStyle: "Left-hand bat", bowlingStyle: "None", teams: ["MI", "RCB", "CSK", "SRH", "Deccan Chargers", "Kochi Tuskers"], captain: true, wicketkeeper: true, active: false, retired: true, overseas: false, iplTitles: 3, debutYear: 2008, keyStrength: "Cut shot" },
  { name: "Karun Nair", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["RR", "RCB", "DC", "PBKS", "KKR", "LSG"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2013 },
  { name: "Mandeep Singh", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["PBKS", "RCB", "DC", "KKR"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2010 },
  { name: "Saurabh Tiwary", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["MI", "RCB", "DD", "RPS"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 1, debutYear: 2008 },
  { name: "Vijay Shankar", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["GT", "SRH", "DC", "CSK"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2014 },
  { name: "Shivam Dube", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm medium", teams: ["CSK", "RCB", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2019, keyStrength: "Massive Spin Hitting" },
  { name: "Rahul Tewatia", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["GT", "RR", "DC", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2014, keyStrength: "Ice-cool Finisher" },
  { name: "Harshal Patel", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["PBKS", "RCB", "DC"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2012, keyStrength: "Dipping Slow Yorkers (Purple Patel)" },
  { name: "T Natarajan", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["SRH", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2017, keyStrength: "Yorkers on Command" },
  { name: "Washington Sundar", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["SRH", "RCB", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2017, keyStrength: "Powerplay Control" },
  { name: "Nitish Rana", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["KKR", "MI"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2016 },
  { name: "Riyan Parag", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2019, keyStrength: "Clean Lofted Drives" },
  { name: "Ravi Bishnoi", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["LSG", "PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2020, keyStrength: "Rapid Googly" },
  { name: "Avesh Khan", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RR", "LSG", "DC", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2017 },
  { name: "Rahul Chahar", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["PBKS", "MI", "RPS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 2, debutYear: 2017 },
  { name: "Jaydev Unadkat", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm fast-medium", teams: ["SRH", "MI", "RR", "RPS", "KKR", "RCB", "DC"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2010 },
  { name: "Prasidh Krishna", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast", teams: ["RR", "KKR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2018 },
  { name: "Krunal Pandya", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["LSG", "MI"], captain: true, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 3, debutYear: 2016 },
  { name: "Dhawal Kulkarni", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["MI", "RR", "GL"], captain: false, wicketkeeper: false, active: false, retired: true, overseas: false, iplTitles: 2, debutYear: 2008 },
  { name: "Siddharth Kaul", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["RCB", "SRH", "KKR", "DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2013 },
  { name: "Rajat Patidar", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2021 },
  { name: "Shahbaz Ahmed", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["SRH", "RCB"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2020 },
  { name: "Abhishek Sharma", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["SRH", "DD"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2018 },
  { name: "Jitesh Sharma", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["PBKS"], captain: true, wicketkeeper: true, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2022 },
  { name: "Prabhsimran Singh", country: "India", role: "Wicketkeeper", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["PBKS"], captain: false, wicketkeeper: true, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2019 },
  { name: "Nehal Wadhera", country: "India", role: "Batsman", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2023 },
  { name: "Ayush Badoni", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["LSG"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2022 },
  { name: "Ramandeep Singh", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm medium", teams: ["KKR", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2022 },
  { name: "Shashank Singh", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["PBKS", "SRH", "DC", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2019, keyStrength: "Late Order Destructive Power" },
  { name: "Ashutosh Sharma", country: "India", role: "Batsman", battingStyle: "Right-hand bat", bowlingStyle: "None", teams: ["PBKS"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2024 },
  { name: "Shreyas Gopal", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["MI", "RR", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2014, keyStrength: "Hat-trick Specialist" },
  { name: "Sandeep Warrier", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm fast-medium", teams: ["GT", "KKR", "RCB", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2019 },
  { name: "Deepak Hooda", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Right-arm offbreak", teams: ["LSG", "PBKS", "SRH", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 1, debutYear: 2015 },
  { name: "Karan Sharma", country: "India", role: "Bowler", battingStyle: "Left-hand bat", bowlingStyle: "Right-arm legbreak", teams: ["RCB", "CSK", "MI", "SRH"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 4, debutYear: 2009, keyStrength: "Consecutive Trophy Wins" },
  { name: "Swapnil Singh", country: "India", role: "All-rounder", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["RCB", "LSG", "KXIP", "MI"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2008 },
  { name: "Mayank Dagar", country: "India", role: "Bowler", battingStyle: "Right-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["RCB", "SRH", "KXIP"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2023 },
  { name: "Mahipal Lomror", country: "India", role: "All-rounder", battingStyle: "Left-hand bat", bowlingStyle: "Left-arm orthodox", teams: ["RCB", "RR"], captain: false, wicketkeeper: false, active: true, retired: false, overseas: false, iplTitles: 0, debutYear: 2018 }
];

// Map standard enrichment defaults to all extra items
const expandedPlayers = extraPlayers.map(p => ({
  ...p,
  imageUrl: p.imageUrl || "https://images.unsplash.com/photo-1531415074968-036ba1b575da?q=80&w=2067&auto=format&fit=crop",
  careerRuns: p.careerRuns || (p.role === "Bowler" ? "150" : "1,800"),
  playingStyle: p.playingStyle || (p.role === "Batsman" ? "Stroke Maker" : p.role === "Bowler" ? "Pace Attacker" : "Clutch Operator"),
  keyStrength: p.keyStrength || "Match Presence",
  eraGeneration: p.retired ? "Historical Greats" : "Modern Dynamic",
  signatureMetric: p.signatureMetric || (p.iplTitles > 0 ? `${p.iplTitles}-Time Champion` : "Impact Performer")
}));

// Concatenate and deduplicate by name
const finalMap = new Map();
existingPlayers.forEach(p => finalMap.set(p.name, p));
expandedPlayers.forEach(p => finalMap.set(p.name, p));

const uniqueFinalList = Array.from(finalMap.values());

console.log("Writing expanded JSON: ", uniqueFinalList.length, " unique players generated.");

fs.writeFileSync(playersFilePath, JSON.stringify(uniqueFinalList, null, 2));
